<?php include('general.php'); ?>

<html>
<head>
<title>Frazier Lab - Internal Website</title>
<link rel="stylesheet" href="/SWHLabPHP/src/browse/style.css">
<?php clipboard_headScript(); ?>
<style>
/* TODO: MOVE MATURE STYLES TO CSS FILE */
li {line-height: 150%;}
.section{
    width: 85%;
    padding-left: 20px;
    padding-top: 2px;
    padding-bottom: 10px;
    padding-right: 4px;
    background-color: white;
    border: 1px solid #25658a;
    border-left: 10px solid #25658a;
    box-shadow: 5px 5px 10px  rgba(0, 0, 0, 0.15); 
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 50px;
}

.sectionMenu{
    font-size: 120%;
    width: 85%;
    padding-left: 20px;
    padding-right: 4px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 50px;
}

.menuSep{
    color: #CCC;
}

iframe{
    display: block;
    width: 100%; 
    border: none;
}


.bannerBottom{
	background-image: url(/SWHLabPHP/src/browse/images/banner_die_blue.png);
    background-size: contain;
    background-repeat: no-repeat;

	padding-top: 20px;
	padding-bottom: 20px;
    background-position: left bottom;
    margin: -8px;
    margin-bottom: 20px;

}
</style>

<script>
function updatePath(){
    var url = document.getElementById("pathForUrlConv").value;

    while (url.indexOf("\\")>=0){
        url = url.replace("\\", "/");
    }
    
    document.getElementById('urlFromPath').href = "invalid path";
    document.getElementById('urlFromPath').innerHTML = "invalid path";

    url = url.replace("x:", "X:");

    if (url.indexOf('X:') == -1) {
        return;
    }
    url = url.replace("X:/", "/X/");
    url = 'http://192.168.1.9'+url;
    document.getElementById('urlFromPath').href = url;
    document.getElementById('urlFromPath').innerHTML = url;
}

// the function is called only on keypresses. This captures mouse pastes.
setInterval(updatePath, 100);

</script>
</head>
<body>
<div class='banner'>
    <div style="font-size: 250%; font-weight: bold; padding-left: 20px; position: relative; top: -15px;">
        Frazier Laboratory
    </div>
    <div style="font-size: 80%; font-style: italic; padding-left: 20px; position: relative; top: -22px;">
        <!--<?php 
        $date_stamp = (new DateTime('', new DateTimeZone('US/Eastern')))->format('Y-m-d H:i:s'); 
        $server_name = $_SERVER['SERVER_ADDR'];
        echo "Page generated by $server_name on $date_stamp";
        ?>-->
        Internal Laboratory Website
        <br>&nbsp;
    </div>
</div>

<br><br><br>

<div class="sectionMenu">
    <a class='menuLink' href='#experiments'>Experiments</a>
    <span class='menuSep'>|</span>
    <a class='menuLink' href='#animal'>Animals</a>
    <span class='menuSep'>|</span>
    <a class='menuLink' href='#surgical'>Surgeries</a>
    <span class='menuSep'>|</span>
    <a class='menuLink' href='#misc'>Miscellaneous</a>
    <span class='menuSep'>|</span>
    <a class='menuLink' href='#browseABF'>ABF Browser</a>
    <span class='menuSep'>|</span>
    <a class='menuLink' href='#fileLocator'>File Locator</a>
</div>

<div class="section"><?php markdown_file_render($markdown_file_folder.'X:\Lab Documents\website\experiments.md'); ?></div>
<div class="section"><?php markdown_file_render($markdown_file_folder.'X:\Lab Documents\website\surgical.md'); ?></div>
<div class="section"><?php markdown_file_render($markdown_file_folder.'X:\Lab Documents\website\animal.md'); ?></div>
<div class="section"><?php markdown_file_render($markdown_file_folder.'X:\Lab Documents\website\misc.md'); ?></div>

<a name='browseABF'></a>
<div class="section">
    <h1>ABF Browser</h1>
    <div>Launch the given folder in the ABF browser website:</div>
    <form action="/SWHLabPHP/recode/src/">
        <input type="hidden" name="view" value="abf">
        <input type="hidden" name="frames">
        <input type="text" name="fldr" value="X:\Data\OTR-Cre\PFC inj eYFP OXT response\abfs" style="width:80%; font-family: monospace;">
        <input type="submit" value="launch">
    </form>
</div>

<a name='fileLocator'></a>
<div class="section">
    <h1>File Locator</h1>
    <div>Input the filename (not the full path) of an ABF and it will be located on the X-drive:</div>
    <iframe src="/SWHLabPHP/src/browse/findABF.php?view=iframe" style='height: 300;'></iframe>
</div>

<div class="section">
    <h1>File or Path Locator</h1>
    <iframe src="/404.php?view=iframe" style='height: 500;'></iframe>
</div>


<a name='browseFolder'></a>
<div class="section">
    <h1>Folder-to-URL</h1>
    <div>Input an X-Drive path and a URL will be generated for it:</div>    
    <input type="text" name="fldr" id="pathForUrlConv" value="X:\Data\OTR-Cre\PFC inj eYFP OXT response\abfs" style="width:80%; font-family: monospace;" onkeypress="updatePath()">
    <div><br>That X-Drive path is available as a URL:<br><a href='' id='urlFromPath'>?</a></code></div>
    <br>


</div>


<div class='bannerBottom' style='height: 400px;'>

</div>

</body>
</html>