<?php include('general.php'); ?>

<html>
<head>
<title>Frazier Lab - Internal Website</title>
<link rel="stylesheet" href="/SWHLabPHP/src/browse/style.css">
<?php clipboard_headScript(); ?>
<style>
/* TODO: MOVE MATURE STYLES TO CSS FILE */
.test{
    width: 85%;
    padding-left: 20px;
    padding-top: 2px;
    padding-bottom: 10px;
    padding-right: 4px;
    background-color: white;
    border: 1px solid #25658a;
    border-left: 10px solid #25658a;
    box-shadow: 5px 5px 10px  rgba(0, 0, 0, 0.15); 
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 50px;
}
</style>
</head>
<body>

<div class='banner'>
    <div style="font-size: 250%; font-weight: bold; padding-left: 20px; position: relative; top: -15px;">
        Frazier Laboratory
    </div>
    <div style="font-size: 80%; font-style: italic; padding-left: 20px; position: relative; top: -22px;">
        <?php 
        $date_stamp = (new DateTime('', new DateTimeZone('US/Eastern')))->format('Y-m-d H:i:s'); 
        $server_name = $_SERVER['SERVER_ADDR'];
        echo "Page generated by $server_name on $date_stamp";
        ?>
        <br>&nbsp;
    </div>
</div>

<br><br><br><br>

<div class="test">
    <?php markdown_file_render($markdown_file_folder.'X:\Lab Documents\website\pinned.md'); ?>
</div>

<div class='test'><h1>Electrophysiology Data Viewers</h1>

    <h2>View a folder of ABFs on the network:</h2>
    <form action="/SWHLabPHP/recode/src/">
        <input type="hidden" name="view" value="abf">
        <input type="hidden" name="frames">
        <input type="text" size="55" name="fldr" value="X:\Data\OTR-Cre\PFC inj eYFP OXT response\abfs" style="font-family: monospace;">
        <input type="submit" value="launch">
    </form>

    <h2>Locate any file on the X-Drive:</h2>
    <form action="/SWHLabPHP/src/browse/search.php">
        <input type="text" size="25" name="match" value="09610008.abf" style="font-family: monospace;">
        <input type="submit" value="search">
    </form>

    <h2>Browse files by hand:</h2>
    <ul>
        <li><a href="/SWHLabPHP/recode/src/?view=abf">ABF Browser</a>
        <li><a href="SWHLabPHP/src/">Linescan Viewer</a>
        <li><a href="/X/">Apache File Browser</a>
    </ul>

</div>

<div class="test"><h1>Surgical Projects</h1>
 
    <h2>Injection Resources</h2>
	<ul>
        <li>Allen Brain Atlas
            <a href='https://scalablebrainatlas.incf.org/mouse/ABA_v3'>common coordinate framework</a>,
            <a href='http://mouse.brain-map.org/experiment/thumbnails/100142143'>reference atlas</a>, 
            <a href="http://help.brain-map.org/download/attachments/2818171/InjectionSites_and_StereotaxicCoordinates.pdf">stereotaxic coordinates (PDF)</a>
    </ul>

    <h2>Surgery Records (animals, coordinates, and verification)</h2>
    <ul>
        <!--<li><?php html_link_file_age('X:\Data\surgeries\surgery_log.txt', "Preliminary Surgeries", "/swhLabPHP/src/browse/surgeries.php?path=X:\Data\surgeries") ?>-->
        <li><a href='/swhLabPHP/src/browse/surgeries.php?path=X:\Data\surgeries'>Preliminary Surgeries</a>
    </ul>
</div>


<div class="test"><h1>Technical</h1>
	<ul>
        <li>View a list of <a href='files/activeFolders/results.csv.html'>active folders (organized by date)</a> for the history of the lab.
        <li>Github projects <a href="https://github.com/swharden/SWHLab">SWHLab</a>, <a href="https://github.com/swharden/SWHLabPHP">SWHLabPHP</a>, <a href="https://github.com/swharden/two-photon">two-photon</a>, and <a href='https://github.com/swharden/swh2p'>SWH2P</a>
        <li>Scott's <a href="/SWHLabPHP/src/browse/scratch.php">scratch.php</a>
        <li>Display this server's <a href="phpinfo.php">PHP information</a>
	</ul>
</div>


<div align="center">
    Looking for something? It may be on the <a href="index_backup_180119.php">old website</a> ...
</div>

<img src="/SWHLabPHP/src/browse/images/banner_die_blue.png" style='width: 100%;'>

</body>
</html>